Fix bug in sequence-parallelism
- modified:
  [`megatron/model/transformer.py`](./megatron/model/transformer.py)

Explicitly, `megatron/model/transformer.py` was missing the
`batch_dim_idx` argument and would crash with:

```python
  File "/lus/flare/projects/Aurora_deployment/AuroraGPT-Testing/foremans/Megatron-DeepSpeed-argonne-lcf/megatron/model/transformer.py", line 811, in forward
    context_layer = self.dist_attn(query_layer, key_layer, value_layer)
  File "/home/jmitche1/anaconda3/envs/anl_2024_q3-official_release/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jmitche1/anaconda3/envs/anl_2024_q3-official_release/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: DistributedAttention.forward() missing 1 required positional argument: 'batch_dim_idx'
```